apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      initContainers:
        - name: run-migrations
          image: borhom11/meatshop-backend:3e116671d53b2d8c510e51cd3e13b30396122781 
          command: ["sh", "-c"]
          args:
          - "python manage.py migrate --no-input && 
             python manage.py createcachetable" 
          envFrom:
          - secretRef:
              name: backend-secret 
      containers:
        - name: backend
          image: borhom11/meatshop-backend:3e116671d53b2d8c510e51cd3e13b30396122781
          envFrom:
            - secretRef:
                name: backend-secret
