apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      initContainers:
        - name: run-migrations
          image: borhom11/meatshop-backend:702287c2135084f708502d701d569b89e0e3534c 
          command: ["sh", "-c"]
          args:
          - "python manage.py migrate --no-input && 
             python manage.py createcachetable" 
          envFrom:
          - secretRef:
              name: backend-secret 
      containers:
        - name: backend
          image: borhom11/meatshop-backend:702287c2135084f708502d701d569b89e0e3534c
          envFrom:
            - secretRef:
                name: backend-secret
