apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.backend.secret.name }}
data:
  DB_NAME: {{ .Values.backend.secret.db_name }}
  DB_PORT: {{ .Values.backend.secret.port }}
  LOCAL_DB_USER: {{ .Values.backend.secret.user }}
  LOCAL_DB_PASSWORD: {{ .Values.backend.secret.password }}
  LOCAL_DB_HOST: {{ print .Release.Name "-" .Values.mysql.statefulset.name "-0." .Release.Name "-" .Values.mysql.service.name | b64enc }}
  DJANGO_SETTINGS_MODULE: {{ .Values.backend.secret.settings_module }} 
  SECRET_KEY: {{ .Values.backend.secret.secret_key }}
  DJANGO_SUPERUSER_EMAIL: {{ .Values.backend.secret.superuser_email }}
  DJANGO_SUPERUSER_USERNAME: {{ .Values.backend.secret.superuser_username }}
  DJANGO_SUPERUSER_PASSWORD: {{ .Values.backend.secret.superuser_password }}
