apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-superuser-job
spec:
  template:
    spec:
      containers:
      - name: django
        image: {{ .Values.backend.deployment.image }}
        command: ["/bin/bash",  "-c"]
        args:
          - "python manage.py createsuperuser --no-input"
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-{{ .Values.backend.deployment.secretName }}
      restartPolicy: Never
  backoffLimit: 4

