apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Values.ingress.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx 
  rules:
    - host: {{ .Values.ingress.frontend_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.frontend.services.name }}
                port:
                  number: {{ .Values.frontend.services.port }}
    - host: {{ .Values.ingress.backend_host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-{{ .Values.backend.services.clusterIP.name }}
                port:
                  number: {{ .Values.backend.services.clusterIP.port }}
