apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.frontend.services.name }}
spec:
  type: NodePort
  selector:
    {{- range $key, $value := .Values.frontend.deployment.labels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  ports:
    - port: {{ .Values.frontend.services.port }}
      targetPort: 80
      name: http

