apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Values.mysql.secret.name }}
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.secret.root_password }}
  MYSQL_DATABASE: {{ .Values.mysql.secret.db }}
  MYSQL_USER: {{ .Values.mysql.secret.user }}

