apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.mysql.job.name }}
spec:
  template:
    spec:
      containers:
      - name: mysql-init-container
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.mysql.secret.name }}
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.mysql.secret.name }}
              key: MYSQL_USER
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-{{ .Values.backend.secret.name }}
              key: LOCAL_DB_HOST
        command: ["/bin/sh", "-c"]
        args:
        - |
          mysql -h${MYSQL_HOST}  -u root -p${MYSQL_ROOT_PASSWORD} <<EOF
          CREATE DATABASE IF NOT EXISTS meatshop;
          EOF
      restartPolicy: Never
